

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    links:
      - "postgres:db"
    networks:
      - app_net
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: pg_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - app_net
    depends_on:
      - postgres

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app_net


volumes:
  postgres-data:
  redis-data:


networks:
  app_net:
    driver: bridge
